substitutions:
  devicename: nas-switch
  location_id: livingroom
  domoticz_device_id: "100"
  name: NAS

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  
<<: !include common/base.yaml

logger:
  esp8266_store_log_strings_in_flash: False
  
switch:
  - platform: gpio
    pin: D6
    id: power
    name: "Power toogle"
    icon: "mdi:PC"
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: power

  - platform: gpio
    pin: D6
    id: force_power
    name: "Force power off"
    icon: "mdi:PC"
    on_turn_on:
    - delay: 5000ms
    - switch.turn_off: force_power

  - platform: gpio
    pin: D7
    id: reset_switch
    on_turn_on:
    - delay: 300ms
    - switch.turn_off: reset_switch

binary_sensor:
  - platform: gpio
    pin: D0
    id: ${name}_power_sensor
    name: "${name} Power State"
    device_class: power
    icon: "mdi:desktop-classic"

