substitutions:
  devicename: weathersation_livingroom
  location_name: 客厅
  domoticz_device_id: "95"

<<: !include weatherstation/base.yaml

sensor: !include_dir_list weatherstation/living_room/sensors/
interval: !include_dir_list weatherstation/living_room/automations/

time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Shanghai

font:
  - file: 'fonts/slkscr.ttf'
    id: font1
    size: 8
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font2
    size: 48
  - file: 'fonts/arial.ttf'
    id: font3
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Living Room");

      // Print time in HH:MM format
      it.strftime(0, 60, id(font2), TextAlign::BASELINE_LEFT, "%H:%M", id(sntp_time).now());

      // Print temperature
      if (id(${devicename}_temp).has_state()) {
        it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(${devicename}_temp).state);
      }

      // Print humidity
      if (id(${devicename}_hum).has_state()) {
        it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f%%", id(${devicename}_hum).state);
      }
