substitutions:
  devicename: weatherstation
  location_id: gongzuojian
  location_name: 工作间
  domoticz_device_id: "92"

<<: !include weatherstation/base.yaml

sensor: !include_dir_list weatherstation/work_room/sensors/
interval: !include_dir_list weatherstation/work_room/automations/
