substitutions:
  devicename: weatherstation_zhuwo
  location_name: 主卧
  domoticz_device_id: "91"
  domoticz_device_id_2: "96"
  domoticz_device_id_3: "97"

<<: !include weatherstation/base.yaml

uart:
  rx_pin: D6
  baud_rate: 9600

switch:
  - platform: gpio
    pin: 
      number: D0
    id: pms_set
    name: "Start measuring"

sensor: !include_dir_list weatherstation/bed_room/sensors/
interval: !include_dir_list weatherstation/bed_room/automations/
