substitutions:
  devicename: weatherstation-ble
  location_id: livingroom
  location_name: Living Room
  domoticz_device_id: "90"  # temp and hum

esphome:
  name: ${devicename}-${location_id}

esp32:
  board: lolin32_lite
  framework:
    type: esp-idf

<<: !include common/base.yaml

mqtt:
  <<: !include common/mqtt.yaml

esp32_ble:
  io_capability: keyboard_display

esp32_ble_tracker:

sensor: !include_dir_list weatherstation/living_room_ble/sensors/
interval: !include_dir_list weatherstation/living_room_ble/automations/
