esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

<<: !include ../common/base.yaml

i2c:
  sda: D1
  scl: D2
  scan: False
  
interval:
  - interval: 60s
    then:
      - lambda: !lambda |-
          id(mqtt_client).publish_json("domoticz/in", [=](JsonObject &root) {
            root["command"] = "udevice";
            root["idx"] = ${domoticz_device_id};
            root["nvalue"] = 0;
            root["svalue"] = String(id(${devicename}_temp).state) + ";" + 
              String(id(${devicename}_hum).state) + ";" +
              String(id(${devicename}_hum_stat).state) + ";" + 
              String(id(${devicename}_bar).state) + ";0";
          });
