sensor:
  - platform: bme280
    temperature:
      name: "${location_name}温度"
      id: "${devicename}_${location_id}_temp"
      oversampling: 16x
      accuracy_decimals: 1
    pressure:
      name: "${location_name}气压"
      id: "${devicename}_${location_id}_bar"
    humidity:
      name: "${location_name}湿度"
      id: "${devicename}_${location_id}_hum"
    address: 0x76
    update_interval: 15s
  - platform: template
    id: "${devicename}_${location_id}_hum_stat"
    internal: True
    accuracy_decimals: 0
    lambda: |-
      float hum = id(${devicename}_${location_id}_hum).state;
      if (hum < 25.0) {
        return 2;
      } else if (hum > 60.0) {
        return 3;
      } else if (hum >= 25.0 && hum <=60.0) {
        return 1;
      } else {
        return 0;
      }
    update_interval: 15s

<<: !include base.yaml
