sensor:
  - platform: bmp280
    temperature:
      name: "${location_name}温度"
      id: temp
      oversampling: 16x
      accuracy_decimals: 1
    pressure:
      name: "${location_name}气压"
      id: bar
    address: 0x76
    update_interval: 15s
  - platform: dht
    pin: D3
    model: DHT11
    temperature:
      name: "${location_name}温度 (DHT)"
    humidity:
      name: "${location_name}湿度"
      id: hum
    update_interval: 15s

<<: !include base.yaml
