wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${devicename}-${location_id}.local

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
